apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: adservice-entry
spec:
  hosts:
  - adservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 9555
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.2
  endpoints:
  - address: 10.50.5.97
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: checkoutservice-entry
spec:
  hosts:
  - checkoutservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 5050
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.3
  endpoints:
  - address: 10.50.5.97
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: currencyservice-entry
spec:
  hosts:
  - currencyservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 7000
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.4
  endpoints:
  - address: 10.50.5.97
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: shippingservice-entry
spec:
  hosts:
  - shippingservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 50051
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.5
  endpoints:
  - address: 10.50.5.97
    ports:
      grpc: 15443
