apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: frontendservice-entry
spec:
  hosts:
  - frontend.prod.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 80
    protocol: http
  resolution: DNS
  addresses:
  - 240.0.0.6
  endpoints:
  - address: 10.50.5.96
    ports:
      http1: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productcatalogservice-entry
spec:
  hosts:
  - productcatalogservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 3550
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.7
  endpoints:
  - address: 10.50.5.96
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cartservice-entry
spec:
  hosts:
  - cartservice.prod.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 7070
    protocol: GRPC
  resolution: DNS
  addresses:
  - 240.0.0.8
  endpoints:
  - address: 10.50.5.96
    ports:
      grpc: 15443
