---
version: 2
plan:
  project-key: IGNW
  key: HIPSTER
  name: Build Demo HIPSTER

# List of plan's stages and jobs
stages:
  - Build the Hipster stage:
    - Build

#Job definition .
Build:
  # tasks:
  #   - script:
  #       - docker build -t gcr.io/boarshead-dsi/demo-Hipster:${bamboo.buildNumber} -t gcr.io/boarshead-dsi/demo-Hipster:latest .
  #       - docker login -u _json_key -p "$(cat /opt/key.json)" https://gcr.io
  #       - docker push gcr.io/boarshead-dsi/demo-Hipster

  # # Job's requirements
  # requirements:
  #    - isRocketFuel
  # Job's artifacts. Artifacts are shared by default.
  artifacts:
     - name: deployments.yaml
       location: ./
       pattern: deployments.yaml
       required: false
       shared: true
     - name: services.yaml
       location: ./
       pattern: services.yaml
       required: false
       shared: true
     - name: deploy.sh
       location: ./
       pattern: deploy.sh
       required: false
       shared: true


---
version: 2
deployment:
  name: Deploy Demo Hipster to K8S
  source-plan: IGNW-HIPSTER

release-naming:
  next-version-name: release.${bamboo.buildNumber}
  applies-to-branches: true
  # auto-increment: true

environments:
  - DEV

DEV:
  triggers:
    - build-success
  tasks:
    - clean
    - artifact-download:
        artifacts:
          - name: deployments.yaml
          - name: services.yaml
          - name: deploy.sh
    - script:
        - ./deploy.sh
